- hosts: all
  gather_facts: false
  vars:
      keypair: ohao
      instance_type: t2.micro
      image: ami-0b9064170e32bde34
      region: us-east-2
  tasks:
    - name: install python
      apt:
       name="python"
       state=present 
       update_cache=true
       
    - name: install python-boto
      apt:
       name="python-boto"
       state=present 
       update_cache=true
     
    - name: make one instance
      ec2: image={{ image }}
           instance_type={{ instance_type }}
           keypair={{ keypair }}
           region={{ region }}
           wait=true
      register: ec2


